# Configuration of Academic
# Documentation: https://sourcethemes.com/academic/
#
# This file is formatted using TOML syntax - learn more at https://learnxinyminutes.com/docs/toml/
# Each configuration section is defined by a name in square brackets (e.g. `[outputs]`).

# Title of your site
title = "Sid Banerjee"

# The URL of your site.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.

# To create public folder, uncomment below and run the following in terminal
# hugo --theme="academic" --buildDrafts
baseurl = "https://sidbanerjee.github.io"
#relativeURLS=true
#CanonifyURLs=true
publishDir = "../Cornell_Sid_Website/public/" # relative to project root


# Enter a copyright notice to display in the site footer.
# To display a copyright symbol, type `&copy;`.
copyright = "&copy; [Sid Banerjee](mailto:sbanerjee@cornell.edu) 2020&ensp;&ensp;&middot; &ensp;&ensp;&ensp;229 Rhodes Hall &ensp;&ensp; "

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = ""

# Enable comments by entering your Disqus shortname
disqusShortname = ""

############################
## Advanced options below ##
############################

# Name of Academic theme folder in `themes/`.
theme = "academic"

# Get last modified date for content from Git?
enableGitInfo = false

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
hasCJKLanguage = false  # Set `true` for Chinese/Japanese/Korean languages.
defaultContentLanguageInSubdir = false

paginate = 10  # Number of items per page in paginated lists.
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true




[outputs]
  home = [ "HTML", "CSS", "RSS", "JSON" ]
  section = [ "HTML", "RSS" ]


[markup]
  defaultMarkdownHandler = "blackfriday"
# Configure BlackFriday Markdown rendering.
#   See: https://gohugo.io/getting-started/configuration/#configure-blackfriday
[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab. See https://github.com/gohugoio/hugo/issues/2424
	angledQuotes = false
	latexDashes = true
  extensions = ["backslashLineBreak"]

[imaging]
  resampleFilter = "lanczos"
  quality = 90
  anchor = "smart"  # Anchor for cropping. Options include Smart and Center.

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"
  #author = "authors"



# menu.toml
# Navigation Links
# To link a homepage widget, specify the URL as a hash `#` followed by the filename of the desired widget in your `content/home/` folder. The weight parameter defines the order that the links will appear in.

[params.menus]
  # Align the main menu to the right of the page? (true/false)
  align_right = true

[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

[[menu.main]]
  name = "Publications"
  url = "#featured"
  weight = 2

[[menu.main]]
  name = "Collaborators"
  url = "#students"
  weight = 3

[[menu.main]]
  name = "Teaching"
  url = "#courses"
  weight = 4

#[[menu.main]]
#  name = "Updates"
#  url = "#updates"
#  weight = 5

#[[main]]
#  name = "Tutorials"
#  url = "/tutorial/"
#  weight = 5

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
 [[menu.main]]
    name = "Bio"
    url = "#CV"
    weight = 6

#[[menu.main]]
#  name = "Contact"
#  url = "#contact"
#  weight = 7

	
	
# languages.toml	
# Languages
#   Create a `[X]` block for each language you want, where X is the language ID. Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[languages.en]
  languageCode = "en-us"
